version: '3'
services:
  app:
    build: .
    volumes:
      - .:/webapp
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
      - log-data:/webapp/log
    depends_on:
      - db
    command: bundle exec puma -C config/puma.rb
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - .:/myapp
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    ports:
      - "80:80"
    depends_on:
      - app
    env_file: production.env

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: