version: '3'
services:
  app:
    build: .
    env_file: .env
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/webapp
      - ./public:/webapp/public
      - ./tmp:/webapp/tmp
      - ./log:/webapp/log
      
  web:
    build:
      context: containers/nginx
    volumes:
      - ./public:/webapp/public
      - ./tmp:/webapp/tmp
    ports:
      - "80:80"
    depends_on:
      - app
    env_file: production.env